### ISSUE TITLE
Storing camera and CPU configuration without saving on JSON files

### ISSUE THREAD

**Issue by jacopoabramo** [SandoghdarLab/PiSCAT#6]
Greetings,

I stumbled upon your library and I was interested in using it in combination with another software to perform background corrections and differential rolling average on real-time acquired camera frames. I understand that these algorithms use some settings class (`CPUConfigurations` and `CameraParameters`) which when creating an instance try to read a JSON file which is written as the first instance is created. Would it be possible to just create an instance without generating the JSON file?

Thank you.

**Comment by po60nani** [comment]
Hi,

If the code cannot find the JSON file, it will use the initial value, which the user can alter to provide various variables, and then store the updated JSON next to the relative path. If you are having trouble with writing permission, you can use the GitHub development version instead of PyPi code and remove the line `self.save_cpu_setting(setting_dic)` from the [CPUConfigurations](https://github.com/SandoghdarLab/PiSCAT/blob/main/piscat/InputOutput/cpu_configurations.py) class. In this situation, whenever you create a new instance of this class, all variables are initialized based on the input defined value, without saving JSON.

Best regards,
